kind: Deployment
apiVersion: apps/v1
metadata:
  name: communication-router
  namespace: oih-dev-ns
  labels:
    app: communication-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-router
  template:
    metadata:
      name: communication-router
      labels:
        app: communication-router
    spec:
      containers:
        - name: communication-router
          image: 'openintegrationhub/communication-router:latest'
          env:
            - name: MONGODB_URI
              value: >-
                mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/webhooks
            - name: RABBITMQ_URI
              value: >-
                amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local
            - name: LISTEN_PORT
              value: '1234'
            - name: LOG_LEVEL
              value: trace
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          securityContext:
            privileged: false
      serviceAccountName: resource-coordinator-account
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
