apiVersion: v1
kind: Service
metadata:
  labels:
    app: communication-router-service
  name: communication-router-service
  namespace: oih-dev-ns
spec:
  ports:
    - name: '1234'
      port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: communication-router
  type: NodePort
