apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: oih-dev-ns
  labels:
    app: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: openintegrationhub/web-ui:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: web-ui
        env: []
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
