apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-directory
  namespace: oih-dev-ns
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: app-directory
    spec:
      containers:
        - name: app-directory
          image: openintegrationhub/app-directory:latest
          env:
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-directory
                  key: iamtoken
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: app-directory
                  key: mongourl
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
            - name: ORIGINWHITELIST
              value: openintegrationhub.com
            - name: PORT
              value: '3000'
            - name: API_BASE
              value: "/api/v1"
            - name: LOGGING_LEVEL
              value: "error"
            - name: DEBUG_MODE
              value: "false"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
