kind: Deployment
apiVersion: apps/v1
metadata:
  name: component-repository
  namespace: oih-dev-ns
  labels:
    app: component-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-repository
  template:
    metadata:
      name: component-repository
      labels:
        app: component-repository
    spec:
      containers:
        - name: component-repository
          image: 'openintegrationhub/component-repository:latest'
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: component-repository
                  key: MONGODB_URI
            - name: RABBITMQ_URI
              value: 'amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local'
            - name: PORT
              value: '1234'
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: component-repository
                  key: IAM_TOKEN
            - name: LOG_LEVEL
              value: trace
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
