apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oih-dev-ingress
  namespace: oih-dev-ns
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "oih-dev-ingress"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: iam.openintegrationhub.com
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 3099
  - host: api.openintegrationhub.com
    http:
      paths:
      - backend:
          serviceName: example-api
          servicePort: 8080
