apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-repository
  namespace: oih-dev-ns
data:
  API_BASE: /api/v1
  DEBUG_MODE: "false"
  INTROSPECT_ENDPOINT_BASIC: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
  INTROSPECT_TYPE: basic
  LOG_LEVEL: error
  ORIGIN_WHITELIST: >-
    openintegrationhub.com,http://web-ui.openintegrationhub.com,https://web-ui.openintegrationhub.com
  PORT: "3000"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
