apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oih-dev-ingress
  namespace: oih-dev-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: iam.example.com
    http:
      paths:
      - backend:
          serviceName: iam
          servicePort: 3099
  - host: skm.example.com
    http:
      paths:
      - backend:
          serviceName: secret-service
          servicePort: 3000
  - host: flow-repository.example.com
    http:
      paths:
      - backend:
          serviceName: flow-repository
          servicePort: 3001
  - host: template-repository.example.com
    http:
      paths:
      - backend:
          serviceName: template-repository
          servicePort: 3001
  - host: auditlog.example.com
    http:
      paths:
      - backend:
          serviceName: audit-log
          servicePort: 3007
  - host: metadata.example.com
    http:
      paths:
      - backend:
          serviceName: meta-data-repository
          servicePort: 3000
  - host: component-repository.example.com
    http:
      paths:
      - backend:
          serviceName: component-repository
          servicePort: 1234
  - host: snapshots-service.example.com
    http:
      paths:
      - backend:
          serviceName: snapshots-service
          servicePort: 1234
  - host: webhooks.example.com
    http:
      paths:
      - backend:
          serviceName: webhooks
          servicePort: 1234
  - host: web-ui.example.com
    http:
      paths:
      - backend:
          serviceName: web-ui
          servicePort: 3000
  - host: attachment-storage-service.example.com
    http:
      paths:
      - backend:
          serviceName: attachment-storage-service
          servicePort: 3002
  - host: data-hub.example.com
    http:
      paths:
      - backend:
          serviceName: data-hub-service
          servicePort: 1234
  - host: ils.example.com
    http:
      paths:
      - backend:
          serviceName: ils
          servicePort: 3003
  - host: app-directory.example.com
    http:
      paths:
      - backend:
          serviceName: app-directory
          servicePort: 3000
  - host: dispatcher-service.example.com
    http:
      paths:
      - backend:
          serviceName: dispatcher-service
          servicePort: 3013
