apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integration-content-repository
  namespace: oih-dev-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-content-repository
    spec:
      containers:
        - name: integration-content-repository
          image: openintegrationhub/integration-content-repository:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: icr
                  key: 'mongourl'
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: icr
                  key: 'iamtoken'
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "https://iam.openintegrationhub.com/api/v1/tokens/introspect"
          resources:
            limits:
              cpu: '0.1'
              memory: 1000Mi
            requests:
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 10
            timeoutSeconds: 1
