apiVersion: v1
kind: ConfigMap
metadata:
  name: web-ui
  namespace: default
data:
  ENDPOINT_APP_DIRECTORY: "http://app-directory.localoih.com/api/v1"
  ENDPOINT_COMPONENT: "http://component-repository.localoih.com"
  ENDPOINT_DISPATCHER: "http://dispatcher-service.localoih.com"
  ENDPOINT_FLOW: "http://flow-repository.localoih.com"
  ENDPOINT_IAM: "http://iam.localoih.com"
  ENDPOINT_METADATA: "http://metadata.localoih.com/api/v1"
  ENDPOINT_SECRETS: "http://skm.localoih.com/api/v1"
  ENDPOINT_WEBHOOKS: "http://webhooks.localoih.com"
  PORT: "3000"
